SellyRental/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from customer import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/', include('customer.urls')),
    path('employee/', include('employee.urls')),
    path('product/', include('product.urls', namespace ='product')),
    path('bid/',include('bid.urls')),
    path('', views.home, name='home'),
    path('accounts/', include('accounts.urls')),
    path('cart/',include('cart.urls',namespace='cart')),
    path('profile/', include('userprofile.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bid/urls.py
from django.urls import path
from . import views
from customer.views import customer_product_detail

urlpatterns = [
    path('', views.bid_list, name='bid_list_all'),
    path('product/<int:product_id>/', views.bid_list, name='bid_list'),
    path('form/<int:product_id>/', views.bid_create, name='bid_create'),
    path('delete/<int:pk>/', views.bid_confirm_delete, name='bid_confirm_delete'),
    path('customer/product/<int:pk>/', customer_product_detail, name='customer_product_detail'),  # use imported view
]

employee/urls.py
from django.urls import path
from employee import views

app_name = 'employee'
urlpatterns = [
    path('', views.employee_list, name='employee_list'),
    path('create/',views.employee_create, name="employee_create"),
    path('update/<int:pk>/', views.employee_update, name='employee_edit'),
    path('delete/<int:pk>/', views.employee_delete, name='employee_delete'),
]

employee/models.py
from django.db import models

class Employee(models.Model):
    name = models.CharField(max_length=100)
    position = models.CharField(max_length=100)

    def __str__(self):
        return self.name

employee/views.py
from django.shortcuts import render, redirect, get_object_or_404

from employee.models import Employee

def employee_list(request):
    employees = Employee.objects.all()
    context ={
        'employees': employees
    }
    return render(request, 'employee/employee_list.html', context)
    
def employee_create(request):
    if request.method == "POST":
        name = request.POST.get('name')
        position = request.POST.get('position')

        employee = Employee()
        employee.name = name
        employee.position = position
        employee.save()

        return redirect('employee:employee_list')
    return render(request, 'employee/employee_create.html')

def employee_update(request,pk):
    employee = get_object_or_404(Employee, pk=pk)

    if request.method == 'POST':
        employee.name = request.POST.get('name')
        employee.position = request.POST.get('position')
        employee.save()
        return redirect('employee:employee_list')
    context = {
        'employee': employee
    }
    return render(request, 'employee/employee_edit.html', context)

def employee_delete(request,pk):
    employee = get_object_or_404(Employee, pk=pk)
    if request.method == 'POST':
        employee.delete()
        return redirect('employee:employee_list')
    context = {
        'employee': employee
    }

    return render(request, 'employee/employee_delete.html',context)

templates/Employee/employee_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Employee</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <h2>Add Employee</h2>

    <form method = "post" action="{%  url 'employee:employee_create' %}">
        {%  csrf_token %}
        <label>Name:</label><br>
        <input type="text" name="name" required><br><br>

        <label> Address:</label><br>
        <input type="text" name ="position" required><br><br>

        <button type="submit">Add</button>
    </form>
    <br>
    <a href="{%  url 'employee:employee_list' %}">Back to Employee List</a>

</body>
</html>

templates/Employee/employee_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Employee Delete</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <h2>Delete Customer</h2>
    <p>Are you sure you want to delete "{{ customer.name }}"</p>
    <form method="post" action="{% url 'employee:employee_delete' employee.id %}">
        {% csrf_token %}
        <button type="submit">Yes, delete</button>
        <a href="{% url 'employee:employee_list' %}">Cancel</a>
    </form>


</body>
</html>

templates/Employee/employee_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Employee</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <h2>Edit Employee</h2>

    <form method="post" action="{% url 'customer_edit' %}">
        {% csrf_token %}
        <label>Name:</label><br>
        <input type="text" name="name" required><br><br>

        <label>Address:</label><br>
        <input type="text" name="address" required><br><br>

        <label>Phone Number:</label><br>
        <input type="text" name="phone_number" required><br><br>

        <button type="submit">Update</button>
    </form>

    <br>
    <a href="{% url 'employee:employee_list' %}">Back to Employee List</a>
</body>
</html>

templates/Employee/employee_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Employee List</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<h2>Employee List</h2>
{{ employees | length }} employees found.
<br><br>

<a href="{% url 'employee:employee_create' %}"> Add Employee</a>

<hr>
<table border="1" cellpadding="5" cellspacing="0">
    <tr>
        <th>pk</th>
        <th>Name</th>
        <th>Position</th>
    </tr>
    {% for employee in employees %}
    <tr>
            <td>{{ employee.pk }}</td>
            <td>{{ employee.name }}</td>
            <td>{{ employee.position }}</td>
            <td>
                <a href="{% url 'employee:employee_edit' employee.id %}">Edit</a>
                <a href="{% url 'employee:employee_delete' employee.id %}" >Delete</a>
            </td>
    </tr>
    {%  empty %}
    <tr><td colspan="4">No employee found.</td></tr>
        {% endfor %}
    </table>

</body>
</html>